// <auto-generated />
using System;
using Apino.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apino.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apino.Domain.Entities.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "تبریز - ولیعصر-",
                            Description = "اولین شعبه آپینو",
                            ImageUrl = "valiasr.jpg",
                            IsActive = true,
                            Slug = "شعبه-ولیعصر-تبریز",
                            Title = "شعبه ولیعصر"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "تبریز - آبرسان-فلکه دانشگاه-",
                            Description = "دومین شعبه آپینو",
                            ImageUrl = "bloor-tower.jpg",
                            IsActive = true,
                            Slug = "شعبه-بلور-تبریز",
                            Title = "شعبه برج بلور"
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.BranchStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("BranchStaff");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BranchId = 1L,
                            Role = 1,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            BranchId = 1L,
                            Role = 2,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            BranchId = 1L,
                            Role = 3,
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<bool>("OnlyOnlinePayment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Apino.Domain.Entities.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PayAtPlace")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CurrentStatusTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Apino.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Apino.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("Apino.Domain.Entities.OrderStatusType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EnglishName = "Created",
                            ShowName = "ثبت شده"
                        },
                        new
                        {
                            Id = 2L,
                            EnglishName = "Paid",
                            ShowName = "پرداخت شده"
                        },
                        new
                        {
                            Id = 3L,
                            EnglishName = "Accepted",
                            ShowName = "تایید شعبه"
                        },
                        new
                        {
                            Id = 4L,
                            EnglishName = "Preparing",
                            ShowName = "در حال آماده‌سازی"
                        },
                        new
                        {
                            Id = 5L,
                            EnglishName = "Done",
                            ShowName = "تحویل شده"
                        },
                        new
                        {
                            Id = 6L,
                            EnglishName = "Canceled",
                            ShowName = "لغو شده"
                        },
                        new
                        {
                            Id = 7L,
                            EnglishName = "Draft",
                            ShowName = "در سبد خرید"
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Stock")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BranchId = 1L,
                            Description = "37 گرم عصاره قهوه",
                            ImageName = "Esperso.jpg",
                            IsActive = true,
                            Price = 1090000m,
                            ProductCategoryId = 2L,
                            ServiceTypeId = 1L,
                            Stock = 20,
                            Title = "اسپرسو (۱۰۰ عربیکا+80/20)"
                        },
                        new
                        {
                            Id = 2L,
                            BranchId = 1L,
                            Description = "37 گرم عصاره قهوه + 220 گرم آب جوش",
                            ImageName = "Americano.jpg",
                            IsActive = true,
                            Price = 1090000m,
                            ProductCategoryId = 2L,
                            ServiceTypeId = 1L,
                            Stock = 20,
                            Title = "آمریکانو (۱۰۰ عربیکا+80/20)"
                        },
                        new
                        {
                            Id = 3L,
                            BranchId = 1L,
                            Description = "37 گرم عصاره قهوه + شکلات کیندر",
                            ImageName = "Kinder.jpg",
                            IsActive = true,
                            Price = 2090000m,
                            ProductCategoryId = 2L,
                            ServiceTypeId = 1L,
                            Stock = 30,
                            Title = "اسپرسو کیندر"
                        },
                        new
                        {
                            Id = 4L,
                            BranchId = 1L,
                            Description = "220 گرم قهوه دم آوری شده دستگاهی",
                            ImageName = "lacP_V0rA2874922.jpg",
                            IsActive = true,
                            Price = 1290000m,
                            ProductCategoryId = 2L,
                            ServiceTypeId = 1L,
                            Stock = 20,
                            Title = "قهوه دمی دستگاهی"
                        },
                        new
                        {
                            Id = 5L,
                            BranchId = 1L,
                            Description = "30 گرم سیروپ وانیل + 37 گرم عصاره قهوه + 220 گرم شیر فوم گرفته شده + یخ",
                            ImageName = "IceLateVanila.jpg",
                            IsActive = true,
                            Price = 1590000m,
                            ProductCategoryId = 7L,
                            ServiceTypeId = 1L,
                            Stock = 10,
                            Title = "آیس لاته وانیل"
                        },
                        new
                        {
                            Id = 6L,
                            BranchId = 1L,
                            Description = "اویشن + لیمو + عسل + دارچین",
                            ImageName = "Damnoosh-floo.jpg",
                            IsActive = true,
                            Price = 1480000m,
                            ProductCategoryId = 7L,
                            ServiceTypeId = 1L,
                            Stock = 15,
                            Title = "دمنوش سرماخوردگی"
                        },
                        new
                        {
                            Id = 7L,
                            BranchId = 1L,
                            Description = "زعفران + هل سبز + گل محمدی + دارچین",
                            ImageName = "Safran-Drink.jpg",
                            IsActive = true,
                            Price = 1580000m,
                            ProductCategoryId = 7L,
                            ServiceTypeId = 1L,
                            Stock = 20,
                            Title = "دمنوش زعفران"
                        },
                        new
                        {
                            Id = 8L,
                            BranchId = 1L,
                            Description = "نعنا، سیروپ بلوکاراسئو، آب پرتقال، آب لیمو، آب انار",
                            ImageName = "DegarDisi.jpg",
                            IsActive = true,
                            Price = 1590000m,
                            ProductCategoryId = 7L,
                            ServiceTypeId = 1L,
                            Stock = 30,
                            Title = "دگردیسی آپینو"
                        },
                        new
                        {
                            Id = 9L,
                            BranchId = 1L,
                            Description = "عرق بیدمشک + گلاب + زعفران",
                            ImageName = "bidmeshkdrink.jpg",
                            IsActive = true,
                            Price = 1080000m,
                            ProductCategoryId = 7L,
                            ServiceTypeId = 1L,
                            Stock = 10,
                            Title = "نوشیدنی عرق بیدمشک"
                        },
                        new
                        {
                            Id = 10L,
                            BranchId = 1L,
                            Description = "دو عدد تخم مرغ + نان",
                            ImageName = "nimroo.jpg",
                            IsActive = true,
                            Price = 1500000m,
                            ProductCategoryId = 6L,
                            ServiceTypeId = 1L,
                            Stock = 10,
                            Title = "نیمرو"
                        },
                        new
                        {
                            Id = 11L,
                            BranchId = 1L,
                            Description = "2 عدد تخم مرغ + 150 گرم سس گوجه + نان",
                            ImageName = "omlet.jpg",
                            IsActive = true,
                            Price = 1900000m,
                            ProductCategoryId = 6L,
                            ServiceTypeId = 1L,
                            Stock = 10,
                            Title = "املت گوجه"
                        },
                        new
                        {
                            Id = 12L,
                            BranchId = 1L,
                            Description = "سرخ شده / هواپز",
                            ImageName = "diet-potato.jpg",
                            IsActive = true,
                            Price = 2000000m,
                            ProductCategoryId = 6L,
                            ServiceTypeId = 1L,
                            Stock = 50,
                            Title = "سیب زمینی رژیمی"
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("PayAtPlace")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BranchId = 1L,
                            CategoryTitle = "فضای کار اشتراکی",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4388),
                            IconName = "place.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "فضای-کار-اشتراکی"
                        },
                        new
                        {
                            Id = 2L,
                            BranchId = 1L,
                            CategoryTitle = "کافه",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4403),
                            IconName = "coffe.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "کافه-1"
                        },
                        new
                        {
                            Id = 3L,
                            BranchId = 1L,
                            CategoryTitle = "کافه خوردنی",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4405),
                            IconName = "coffe.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "کافه-خوردنی-1"
                        },
                        new
                        {
                            Id = 4L,
                            BranchId = 1L,
                            CategoryTitle = "نوشیدنی سرد",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4406),
                            IconName = "coffe.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "نوشیدنی-سرد-1"
                        },
                        new
                        {
                            Id = 5L,
                            BranchId = 1L,
                            CategoryTitle = "فروشگاه",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4408),
                            IconName = "shop.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "فروشگاه-1"
                        },
                        new
                        {
                            Id = 6L,
                            BranchId = 1L,
                            CategoryTitle = "میز مطالعه عمومی",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4409),
                            IconName = "place.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "میز-مطالعه-عمومی-1"
                        },
                        new
                        {
                            Id = 7L,
                            BranchId = 1L,
                            CategoryTitle = "استودیو",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4411),
                            IconName = "studio.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "استودیو-1"
                        },
                        new
                        {
                            Id = 8L,
                            BranchId = 1L,
                            CategoryTitle = "فضای کار اشتراکی",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4412),
                            IconName = "place.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "فضای-کار-اشتراکی"
                        },
                        new
                        {
                            Id = 9L,
                            BranchId = 2L,
                            CategoryTitle = "فضای کار اشتراکی",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4413),
                            IconName = "palce.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "فضای-کار-اشتراکی-2"
                        },
                        new
                        {
                            Id = 10L,
                            BranchId = 2L,
                            CategoryTitle = "کافه",
                            CreationDateTime = new DateTime(2026, 1, 31, 0, 7, 6, 449, DateTimeKind.Local).AddTicks(4415),
                            IconName = "coffe.png",
                            IsActive = true,
                            PayAtPlace = true,
                            Slug = "کافه-2"
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.ServiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsSessionBased")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceTypeEnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsSessionBased = true,
                            ServiceTypeEnglishName = "CountByUse",
                            ServiceTypeTitle = "جلسه ای"
                        },
                        new
                        {
                            Id = 2L,
                            IsSessionBased = false,
                            ServiceTypeEnglishName = "Monthly",
                            ServiceTypeTitle = "ماهانه"
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDatetime = new DateTime(2026, 1, 30, 20, 37, 6, 449, DateTimeKind.Utc).AddTicks(4508),
                            IsActive = true,
                            Mobile = "09143010428",
                            Role = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreationDatetime = new DateTime(2026, 1, 30, 20, 37, 6, 449, DateTimeKind.Utc).AddTicks(4509),
                            IsActive = true,
                            Mobile = "09359719229",
                            Role = 2
                        },
                        new
                        {
                            Id = 3L,
                            CreationDatetime = new DateTime(2026, 1, 30, 20, 37, 6, 449, DateTimeKind.Utc).AddTicks(4510),
                            IsActive = true,
                            Mobile = "09121234567",
                            Role = 3
                        },
                        new
                        {
                            Id = 4L,
                            CreationDatetime = new DateTime(2026, 1, 30, 20, 37, 6, 449, DateTimeKind.Utc).AddTicks(4511),
                            IsActive = true,
                            Mobile = "09127654321",
                            Role = 3
                        });
                });

            modelBuilder.Entity("Apino.Domain.Entities.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelegramId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Apino.Domain.Entities.UserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Apino.Domain.Entities.BranchStaff", b =>
                {
                    b.HasOne("Apino.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apino.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apino.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Apino.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apino.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Apino.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Order", b =>
                {
                    b.HasOne("Apino.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apino.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Apino.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apino.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Apino.Domain.Entities.OrderStatus", b =>
                {
                    b.HasOne("Apino.Domain.Entities.Order", "Order")
                        .WithMany("Statuses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apino.Domain.Entities.OrderStatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Product", b =>
                {
                    b.HasOne("Apino.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apino.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Apino.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("Apino.Domain.Entities.Branch", "Branch")
                        .WithMany("Categories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Apino.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("Apino.Domain.Entities.User", null)
                        .WithOne("UserProfile")
                        .HasForeignKey("Apino.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Apino.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("Apino.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Apino.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Apino.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Apino.Domain.Entities.User", b =>
                {
                    b.Navigation("Tokens");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
